[[main]]
URL = "/"
name = "Home"
weight = 1

[[main]]
URL = "/faq/"
name = "FAQs"
weight = 2

[[main]]
URL = "/contact/"
name = "Support"
weight = 3

[[main]]
weight = 4
name = "Legalities"
URL = "/legalities/"

[[footer]]
URL = "/legalities/"
name = "Legalities"
weight = 7

[[footer]]
URL = "/disclaimer/"
name = "Disclaimer"
weight = 5

[[footer]]
URL = "/cookies/"
name = "Cookie Policy"
weight = 4

[[footer]]
URL = "/privacy-policy/"
name = "Privacy Policy"
weight = 3

[[footer]]
URL = "/terms-and-conditions/"
name = "Terms & Conditions"
weight = 2